# Generated by Django 5.0.4 on 2024-09-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('para', models.CharField(max_length=20000000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
